### PR TITLE
changed update routine to reflect the specified SERVICE name.

### PR DESCRIPTION
**Pull request by Angel0fDarkness**
See my issue for details: https://github.com/Ahtenus/minecraft-init/issues/16

### CODE REVIEW

**Comment by Benni-chan** [comment]
with only these changes, it would be impossible to run a vanilla server without bukkit, since the update function will always save the latest craftbukkit as $SERVICE
i believe, it would be necessary to add another config var to set, if you want to run vanilla or bukkit.

i'll have a look at it in a few days...

**Comment by Angel0fDarkness** [comment]
I added a check if the SERVICE variable contains either "minecraft" (for the original minecraft server) or "bukkit" (for the craftbukkit server) befor applying the upgrade.
If another server will be added later it is expandable through adding a new case.

Unfortunately I am currently not able to check if this works as expected because my internet connection seems to be on strike ;)

**Comment by Ahtenus** [comment]
Won't this make bukkit server overwrite the vanilla server?

**Comment by Ahtenus** [comment]
Sorry for my earlier post, hadn't updated so only saw the original post.

Your new solution that checks if the variable contains either bukkit or minecraft feels awkward. It's possible that someone renames their bukkit server to something containing minecraft.

**Pull request closed without merging**
