### PR TITLE
Fixed a bug and made lots of improvements

### PR DESCRIPTION
**Pull request by jbondhus**
I've corrected an error with the screen where the screen is identical to the username causing the script to fail - it was very difficult to fix and took me a week to figure out what was wrong - even the person who made the new section that caused it had no clue. I've added an option to force-kill the server in an emergency (don't worry, it warns of the ramifications and riskiness of doing so and asks if the user would still like to continue). I've also added an option to open the screen console with the script, as well as to specify both the text appended to the rolled logs and whether the user wants them compressed or not. Of course I've also cleaned up the formatting/comments/indentation in the meantime, as well as improved the log rolling function vastly and moved it to the command section at the end to eliminate some redundancy.

I've freely spent hours of work on these changes, please consider merging them into the main script, as I believe they will drastically improve the project. If you have any changes you want me to make, feel free to email me at my posted email address.

### CODE REVIEW

**Comment by sockenklaus** [comment]
:+1:

**Comment by jbondhus** [comment]
I'm thinking of fixing that bug too later by having grep search the process list for more specific terms, such as the actual  screen command that is run instead of just the screen name. That way we can eliminate that major bug where the script doesn't launch if the screen name is the same as the username (the default settings). I want to wait until these commits are merged into the main repository so I can start off a fresh base though.

**Comment by jbondhus** [comment]
Fixed the bug, let me update the pull request. :)

**Comment by Ahtenus** [comment]
Nice one!

**Pull request merged**
