### PR TITLE
Added a command that opens the minecraft server console

### PR DESCRIPTION
**Pull request by jbondhus**
It is now possible to go "/etc/init.d/minecraft screen" to launch the minecraft server console. I organized the functions and commands alphabetically, added a function called "pause", that waits for the user to hit enter, and made minor changes to commenting. I also moved the initial code that runs every time into a function called initialize, that calls every time the script runs. I know it looks like I removed and deleted a lot, but that's just because I moved  functions so that they are ordered alphabetically. I have tested it out and there are no problems so far.

UPDATE: I forgot to call the "initialize" function.

### CODE REVIEW

**Comment by Ahtenus** [comment]
Alphabetically just doesn't make sense.

**Comment by jbondhus** [comment]
Are the functions even in any order right now? Alphabetically makes more sense then not being organized. Most computers organize files alphabetically by default, so why not organize our functions alphabetically? It would make it easier to find functions when you know that function "world-backup" is going to be close to the end instead of randomly in the middle.

**Comment by jbondhus** [comment]
If you would like, I can revert it to non-alphabetical. I have many minor changes that would probably be a good fit in the main script, such as options to not compress the logs, and a command that pulls up the console.

PS: I know, I've been inactive for a while, I've been working full-time, and I'm starting college this Fall, going for a MBA and BS in Computer Science.

**Comment by Ahtenus** [comment]
Sure go right ahead.

**Pull request closed without merging**
